name: Master merged

on:
  push:
    branches: [ 'master' ]
  workflow_dispatch:
    branches: [ 'master' ]

concurrency:
  group: 'master-merge'
  cancel-in-progress: true

# Add "id-token" with the intended permissions.
permissions:
  contents: 'write'
  id-token: 'write'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22.12'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: |
          npm install

      - name: CI
        run: |
          npm ci

      - name: Test
        run: |
          npm test

      - name: Bump Version
        if: success()
        run: |
          git config --global user.email "url-signer-nodejs@ioriver.io"
          git config --global user.name "url-signer-nodejs"
          git config --global credential.helper store
          git config --global credential.helper 'cache --timeout=3600'
          npm version minor
          git push

  publish:
    needs: [ build ]
    runs-on: ubuntu-22.04
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22.12'
          registry-url: 'https://registry.npmjs.org'

      - name: CI
        run: |
          npm ci

      - name: Publish to npm
        run: |
          npm publish --access public